# Generated by Django 6.0.4 on 2026-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('urgente', models.BooleanField(default=False)),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('en_camino', 'En camino'), ('entregado', 'Entregado')], default='registrado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
