# Generated by Django 6.0.4 on 2026-09-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_alter_pedido_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='medio_asignado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_asignacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
