# Generated by Django 6.0.4 on 2026-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_pedido_medio_asignado_pedido_motivo_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
