# Generated by Django 6.0.4 on 2026-09-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_pedido_costo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tiempo_estimado_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
