# Generated by Django 6.0.4 on 2026-09-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_pedido_tiempo_estimado_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
